# Generated by Django 3.1.6 on 2021-03-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecthardware',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
