# Generated by Django 3.1.6 on 2021-03-03 13:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(default='No description', max_length=200)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('product_id', models.CharField(max_length=50)),
                ('image_name', models.CharField(max_length=50)),
                ('available', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.category')),
            ],
        ),
        migrations.CreateModel(
            name='TakenHardwareArchieve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='return date')),
                ('quantity', models.IntegerField(default=1)),
                ('description', models.CharField(default='', max_length=300)),
                ('hardware', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hardware.hardware')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TakenHardware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateTimeField(auto_now_add=True, verbose_name='take date')),
                ('date_to', models.DateTimeField(default=datetime.datetime(2021, 4, 2, 13, 24, 2, 644902), verbose_name='return date')),
                ('quantity', models.IntegerField(default=1)),
                ('description', models.CharField(default='', max_length=300)),
                ('hardware', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='hardware.hardware')),
                ('taker', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HardwareAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('totalquantity', models.IntegerField(default=0)),
                ('hardware', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='hardware.hardware')),
            ],
        ),
    ]
