# Generated by Django 3.1.6 on 2021-03-03 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardwareamount',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hardwareamount',
            name='totalquantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='takenhardware',
            name='date_to',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 2, 14, 35, 55, 399192), verbose_name='return date'),
        ),
        migrations.AlterField(
            model_name='takenhardware',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='takenhardwarearchieve',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
