# Generated by Django 3.1.6 on 2021-03-03 14:47

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0002_auto_20210303_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardwareamount',
            name='quantity',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='takenhardware',
            name='date_to',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 2, 14, 47, 12, 176769), verbose_name='return date'),
        ),
    ]
